version: "2"
services:
  bugs:
    build:
      context: .
      dockerfile: bugs/Dockerfile
    restart: always
    volumes:
    - .:/go/src/kit-test
    container_name: bugs
    ports:
    - 8801:8081
  notifications:
    build:
      context: .
      dockerfile: notifications/Dockerfile
    restart: always
    volumes:
    - .:/go/src/kit-test
    container_name: notifications
    ports:
    - 8802:8082
  users:
    build:
      context: .
      dockerfile: users/Dockerfile
    restart: always
    volumes:
    - .:/go/src/kit-test
    container_name: users
    ports:
    - 8800:8081
